export const FETCH_BLOG_START = 'FETCH_BLOG_START';
export const FETCH_BLOG_END = 'FETCH_BLOG_END';
export const FETCH_BLOG_DETAIL_START = 'FETCH_BLOG_DETAIL_START';
export const FETCH_BLOG_DETAIL_END = 'FETCH_BLOG_DETAIL_END';