export const FETCH_BLOG_PENDING = 'FETCH_BLOG_PENDING';
export const FETCH_BLOG_FULFILLED = 'FETCH_BLOG_FULFILLED';
export const FETCH_BLOG_REJECTED = 'FETCH_BLOG_REJECTED';
export const FETCH_BLOG_DETAIL_PENDING = 'FETCH_BLOG_DETAIL_PENDING';
export const FETCH_BLOG_DETAIL_FULFILLED = 'FETCH_BLOG_DETAIL_FULFILLED';
export const FETCH_BLOG_DETAIL_REJECTED = 'FETCH_BLOG_DETAIL_REJECTED';